# Generated by Django 5.0 on 2023-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classe_matiere_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
